# Generated by Django 4.1.6 on 2023-04-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_follower_user_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='follows',
        ),
    ]
