# Generated by Django 4.1.6 on 2023-04-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_follower_user_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='followings',
        ),
    ]
