# Generated by Django 4.1.6 on 2023-02-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
