# Generated by Django 4.1.6 on 2023-02-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_last_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_price',
        ),
    ]
